workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: 6c07076c-aac2-4830-b38a-0be127e029dd
        APP_STORE_CONNECT_KEY_IDENTIFIER: 5B3RGV345J
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFB...)
      flutter: 3.24.0
      xcode: 16.0
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - flutter doctor -v
      - |
        # Clean and ensure dependencies are installed using the custom Podfile
        cd ios
        pod deintegrate
        pod cache clean --all
        pod install
        cd ..
      - keychain initialize
      - app-store-connect fetch-signing-files "com.mcmaster.mmamse" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --release --no-codesign --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: 5B3RGV345J
        issuer_id: 6c07076c-aac2-4830-b38a-0be127e029dd
        submit_to_testflight: true
