name: mma_mse
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  path_provider: ^2.1.2
  url_launcher: ^6.1.13
  google_fonts: ^6.2.0
  
  # Mobile-only packages
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  youtube_player_iframe: ^4.0.4
  page_transition: ^2.0.9
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0
  csv: ^5.0.2
  permission_handler: ^10.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_zoom_drawer: ^3.1.1
  lottie: ^2.6.0
  clay_containers: ^0.3.2

flutter_icons:
  image_path: "assest/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

  
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assest/lot/
   - assest/csv/Rockwell/RockWellC.csv
   - assest/csv/Rockwell/RockwellB.csv
   - assest/csv/Rockwell/A.csv
   - assest/csv/Rockwell/D.csv
   - assest/csv/Rockwell/superficial15.csv
   - assest/csv/shore.csv
   - assest/csv/Brinell3000.csv
   - assest/csv/Brinell500.csv
   - assest/csv/Rockwell/superf30.csv
   - assest/csv/vicker.csv
   - assest/test/hdtbg1.jpg
   - assest/test/ttbg1.jpg
   - assest/logocolor.png
   - assest/bglay.png
   - assest/picture1.png
   - assest/picture2.png
   - assest/equipment/theory/automatic_cutter/posserabracut.png
   - assest/search/tools/phase.jpg
   - assest/search/tools/unit.jpg
   - assest/search/tools/erf.png
   - assest/search/tools/Picture2.jpg
   - assest/JHE.jpg
   
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
